### ISSUE TITLE
Feature Request: Ability to Track Plugins that are "Safe"

### ISSUE THREAD

**Issue by Caffa** [chrisgrieser/obsidian-divide-and-conquer#12]
### Feature Requested

Requesting a way to print currently enabled plugin list or mark plugins as safe, because you don't know which plugin you enabled is the buggy plugin?

I can disable all, enable half (and no bug) - then want to mark that half as safe plugins, 

then continue on to enable half of disabled then if bug, mark that half as potential issues and only enable those - then narrow down by disabling them and switching between those

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by geoffreysflaminglasersword** [comment]
It sounds like what you want is accomplished with the new changes, so I'm closing this
