### ISSUE TITLE
Re-create `Count Plugins` command

### ISSUE THREAD

**Issue by chrisgrieser** [chrisgrieser/obsidian-divide-and-conquer#8]
followup from #2 
> Bisect, un-bisect, re-bisect replace those three commands, and also get rid of the need for "enable all plugins" as un-bisecting the top level would do the same thing. Personally I also don't think there's a need for "disable all plugins" considering you can just turn on safe mode, and I don't really understand the point of the "count" command.

@geoffreysflaminglasersword The purpose of disabling all instead of safe mode is that you can *afterwards* turn on a single plugin manually, to test things with all plugins except that one plugin disabled. Safe Mode doesn't help you here, since it turns of everything, and then recreates the previous state. that situation also makes enabling all plugins useful when you are finished.

However, with your new settings for filtering certain plugins, those two are probably obsolete and unnecessary now. 

---

However, I think the counting of plugins should indeed be re-added. It's a minor thing, but it is useful to keep track of how many plugins are currently enabled/disabled, e.g. when you are interrupted while bisecting.

**Comment by geoffreysflaminglasersword** [comment]
> followup from #2
> 
> > Bisect, un-bisect, re-bisect replace those three commands, and also get rid of the need for "enable all plugins" as un-bisecting the top level would do the same thing. Personally I also don't think there's a need for "disable all plugins" considering you can just turn on safe mode, and I don't really understand the point of the "count" command.
> 
> @geoffreysflaminglasersword The purpose of disabling all instead of safe mode is that you can _afterwards_ turn on a single plugin manually, to test things with all plugins except that one plugin disabled. Safe Mode doesn't help you here, since it turns of everything, and then recreates the previous state. that situation also makes enabling all plugins useful when you are finished.
> 
> However, with your new settings for filtering certain plugins, those two are probably obsolete and unnecessary now.
> 
> However, I think the counting of plugins should indeed be re-added. It's a minor thing, but it is useful to keep track of how many plugins are currently enabled/disabled, e.g. when you are interrupted while bisecting.

I think you're right, though I'd add that maybe the count (as well as buttons for the 5 commands I added) would be really well suited in the plugin tab UI itself. Similar to [Hotkey Helper](https://github.com/pjeby/hotkey-helper#:~:text=Hotkey%20Helper%3A%20Easier%20Hotkey%20and%20Options%20Management%20for%20Obsidian,-New%20in...&text=This%20plugin%20makes%20it%20easier,plugin's%20options%20or%20hotkey%20assignments.) and [Plugin Changelogs](https://github.com/phibr0/obsidian-plugin-changelogs) but at the top of the list with the reload button of course. If I get the time I'd like to implement that but frontend isn't my strong suit yet.

If you ever got around to it, a function call that updates the count could be added to [composed](https://github.com/chrisgrieser/obsidian-divide-and-conquer/blob/a1fc82022d1c7454956f801e664e8929da98cd57/main.ts#L58) very simply
